
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: example7.com
    http:
      paths:
      - backend:
          serviceName: analytics-server
          servicePort: 9080
        
